language: go
go:
  - "1.11.x"
  - "1.12.x"
matrix:
  include:
    - go: "1.13.x"
      script:
        - make ci
      after_success:
        - bash <(curl -s https://codecov.io/bash)
script:
  - GO111MODULE=on make test
